### ISSUE TITLE
Client Crash - Ticking Player (Unstable Block)

### ISSUE THREAD

**Issue by Darkfiend009** [Hugman76/Mubble#29] opened 2019-02-18 10:04 UTC
A player of mine can no longer connect to the server. When he joins, the server console sends a ticking player error based on a packet and then disconnects the player from the server. Here is what the console shows:

https://pastebin.com/BRHv0cYZ

I checked the player data to see if he has any unstable block in his inventory and he does not. I'm not sure how to resolve the issue so the player can connect. 

Version: Mubble-1.3-pre6-(1.12.2)
Forge: 2811

**Comment by Hugman76** [comment] 2019-02-21 22:00
### Thanks for the report!
However, this bug is a duplicate of #25.
Note: Try using a latest version

**Comment by Hugman76** [comment] 2019-03-28 20:55
### Thanks for the report!
This bug has been fixed in v**1.3**.

**Closed by Hugman76** 2019-03-28 20:55 UTC
Labels: bug
